Repository fravilpaejeszamgueTFG/EscapeStalingradZ, pull requests merged in 2024-04, with the labels that each got.

#141 propiedades FUBAR
  Config/DefaultEngine.ini
  Content/GameMode/BP_EscapeStalingradZGameModeBase.uasset
  Content/GameMode/BP_EscapeStalingradZGameModeBase1.uasset
  Content/Maps/FUBAR.umap
  Content/Maps/FUBAR_BuiltData.uasset
  Content/Maps/InitialMap.umap
  Content/Maps/InitialMap_BuiltData.uasset
  Content/player/BP_PlayerC.uasset
  Source/EscapeStalingradZ/character/PlayerCharacter.cpp
  Source/EscapeStalingradZ/turn/Turn.cpp
  Source/EscapeStalingradZ/widget/WPlayerInfo.cpp
Labels: Mapas

#145 Iconos
  Content/Art/Images/backpack.uasset
  Content/Art/Images/clutch.uasset
  Content/Art/Images/door-rotation.uasset
  Content/Art/Images/door_1.uasset
  Content/Art/Images/menu.uasset
  Content/Art/Images/opened-door-aperture-rotation.uasset
  Content/Art/Images/opened-door-aperture.uasset
  Content/Art/Images/shooting-star.uasset
  Content/Character/BP_PlayerCharacter.uasset
  Content/Maps/FUBAR.umap
  Content/Maps/FUBAR_BuiltData.uasset
  Content/Maps/WakeUp.umap
  Content/Widgets/BP_UserHUD.uasset
  Content/Widgets/BP_WDoor.uasset
  Content/Widgets/BP_WPlayerInfo.uasset
  Content/Widgets/BP_WStun.uasset
  Content/Widgets/BP_WZombieInfo.uasset
  Content/Widgets/Combat/BP_HitText.uasset
  Content/Widgets/Combat/BP_WDiceSpreadCombat.uasset
  Content/Widgets/Combat/BP_WDicesCombat.uasset
  Content/Zombie/BP_Zombie.uasset
  Content/art/images/door.uasset
  Content/art/images/door_2.uasset
  Content/grid/BP_Grid.uasset
  Content/grid/gridModifiers/BP_DoorModifier.uasset
  Content/misc/BP_AnimatedTextAttack.uasset
  Content/misc/BP_DoorIcon.uasset
  Content/misc/BP_StunIcon.uasset
  Content/player/BP_PlayerPawn.uasset
  Source/EscapeStalingradZ/Grid/Grid.h
  Source/EscapeStalingradZ/Grid/GridModifierDoor.cpp
  Source/EscapeStalingradZ/Grid/GridModifierDoor.h
  Source/EscapeStalingradZ/character/PlayerCharacter.cpp
  Source/EscapeStalingradZ/character/PlayerCharacter.h
  Source/EscapeStalingradZ/misc/AnimatedTextAttack.cpp
  Source/EscapeStalingradZ/misc/AnimatedTextAttack.h
  Source/EscapeStalingradZ/misc/DoorIcon.cpp
  Source/EscapeStalingradZ/misc/DoorIcon.h
  Source/EscapeStalingradZ/misc/StunIcon.cpp
  Source/EscapeStalingradZ/misc/StunIcon.h
  Source/EscapeStalingradZ/player/actions/ActionOpenCloseDoor.cpp
  Source/EscapeStalingradZ/widget/WDiceSpreadCombat.cpp
  Source/EscapeStalingradZ/widget/WDiceSpreadCombat.h
  Source/EscapeStalingradZ/widget/WDicesCombat.cpp
  Source/EscapeStalingradZ/widget/WDicesCombat.h
  Source/EscapeStalingradZ/widget/WReleaseLock.cpp
  Source/EscapeStalingradZ/widget/WZombieInfo.cpp
  Source/EscapeStalingradZ/widget/WZombieInfo.h
  Source/EscapeStalingradZ/zombies/Zombie.cpp
  Source/EscapeStalingradZ/zombies/Zombie.h
Labels: Interfaces

#150 Nivel Un amigo Sangrará
  Content/Art/Images/STASH_Mat.uasset
  Content/Art/Images/WAKE_UP_-_TIME_TO_DIE_Mat.uasset
  Content/Art/Materials/A_FRIEND_WILL_BLEED_Mat.uasset
  Content/Art/Materials/STASH_Mat.uasset
  Content/Art/Materials/WAKE_UP_-_TIME_TO_DIE_Mat.uasset
  Content/Maps/AFriendWillBleed.umap
  Content/Widgets/Objectives/BP_WObjectives.uasset
  Source/EscapeStalingradZ/player/PlayerC.cpp
Labels: Mapas

#151 Nivel avanza
  Content/Art/Materials/MOVE_ALONG_Mat.uasset
  Content/Maps/MoveAlong.umap
  Content/Maps/Stash.umap
  Content/Maps/WakeUp.umap
  Content/Widgets/Objectives/BP_WObjectives.uasset
  Source/EscapeStalingradZ/player/PlayerC.cpp
Labels: Mapas

#153 iconos de busqueda
  Content/Maps/AFriendWillBleed.umap
  Content/Maps/FUBAR.umap
  Content/Maps/FUBAR_BuiltData.uasset
  Content/Maps/MoveAlong.umap
  Content/Maps/Stash.umap
  Content/Widgets/BP_WDoor.uasset
  Content/Widgets/BP_WStun.uasset
  Content/Widgets/BP_WZombieInfo.uasset
  Content/Widgets/Misc/BP_WAlphaO.uasset
  Content/Widgets/Misc/BP_WDoor.uasset
  Content/Widgets/Misc/BP_WSearchO.uasset
  Content/Widgets/Misc/BP_WStun.uasset
  Content/Widgets/Misc/BP_WZombieInfo.uasset
  Content/Zombie/BP_Zombie.uasset
  Content/grid/BP_Grid.uasset
  Content/misc/BP_AlphaSearchIcon.uasset
  Content/misc/BP_DoorIcon.uasset
  Content/misc/BP_StunIcon.uasset
  Content/misc/BP_TileSearchedIcon.uasset
  Source/EscapeStalingradZ/Grid/Grid.cpp
  Source/EscapeStalingradZ/Grid/Grid.h
  Source/EscapeStalingradZ/player/actions/ActionSearch.cpp
  Source/EscapeStalingradZ/turn/Turn.cpp
  Source/EscapeStalingradZ/widget/WSearchDie.cpp
  Source/EscapeStalingradZ/zombies/Zombie.cpp
  Source/EscapeStalingradZ/zombies/Zombie.h
Labels: Interfaces

#154 feat: Habilidades Alpha
  Source/EscapeStalingradZ/turn/Turn.cpp
  Source/EscapeStalingradZ/turn/Turn.h
  Source/EscapeStalingradZ/zombies/Zombie.cpp
Labels: Zombie

#157 Liberación segundo personaje
  Content/Maps/AFriendWillBleed.umap
  Content/Maps/WakeUp.umap
  Content/Widgets/Actions/BP_WOtherActions.uasset
  Source/EscapeStalingradZ/Grid/Grid.cpp
  Source/EscapeStalingradZ/character/PlayerCharacter.cpp
  Source/EscapeStalingradZ/character/PlayerCharacter.h
  Source/EscapeStalingradZ/player/PlayerC.cpp
  Source/EscapeStalingradZ/player/PlayerC.h
  Source/EscapeStalingradZ/player/actions/ActionFreeNewCharacter.cpp
  Source/EscapeStalingradZ/player/actions/ActionFreeNewCharacter.h
  Source/EscapeStalingradZ/widget/UserHUD.h
  Source/EscapeStalingradZ/widget/WActions.cpp
  Source/EscapeStalingradZ/widget/WOtherActions.cpp
  Source/EscapeStalingradZ/widget/WOtherActions.h
  Source/EscapeStalingradZ/widget/WPlayerInfo.cpp
  Source/EscapeStalingradZ/widget/WSearchDie.cpp
  Source/EscapeStalingradZ/widget/WSelectCharacterToFree.cpp
Labels: Mapas

#159 Intercambio de objetos entre personajes
  Content/Maps/AFriendWillBleed.umap
  Content/Maps/MoveAlong.umap
  Content/Widgets/Actions/BP_WActions.uasset
  Content/Widgets/Actions/BP_WMovementAction.uasset
  Content/Widgets/Actions/BP_WOtherActions.uasset
  Content/Widgets/Actions/BP_WSelectCoveringType.uasset
  Content/Widgets/Actions/BP_WSelectMovementType.uasset
  Content/Widgets/BP_UserHUD.uasset
  Content/Widgets/BP_WBetweenScenaries.uasset
  Content/Widgets/BP_WExchangeEquipment.uasset
  Content/Widgets/BP_WInventory.uasset
  Source/EscapeStalingradZ/character/PlayerCharacter.cpp
  Source/EscapeStalingradZ/character/PlayerCharacter.h
  Source/EscapeStalingradZ/player/actions/ActionExchangeEquipment.cpp
  Source/EscapeStalingradZ/player/actions/ActionExchangeEquipment.h
  Source/EscapeStalingradZ/widget/UserHUD.cpp
  Source/EscapeStalingradZ/widget/UserHUD.h
  Source/EscapeStalingradZ/widget/WBetweenScenarios.cpp
  Source/EscapeStalingradZ/widget/WExchangeEquipment.cpp
  Source/EscapeStalingradZ/widget/WExchangeEquipment.h
  Source/EscapeStalingradZ/widget/WOtherActions.cpp
  Source/EscapeStalingradZ/widget/WOtherActions.h
Labels: Personaje

#160 habilidades de personaje (10 exp)
  Source/EscapeStalingradZ/character/PlayerCharacter.cpp
Labels: Prioridad 4, Personaje
