Repository fravilpaejeszamgueTFG/EscapeStalingradZ, pull requests merged in 2024-01, with the labels that each got.

#87 Implementar sistema movimiento hacia adelante
  Config/DefaultEngine.ini
  Config/DefaultInput.ini
  Content/BP_Grid.uasset
  Content/Character/BP_PlayerCharacter.uasset
  Content/Maps/InitialMap.umap
  Content/Maps/InitialMap_BuiltData.uasset
  Content/Widgets/W_MovementAction.uasset
  Content/art/materials/prueba.uasset
  Content/grid/BP_Grid.uasset
  Content/mapa_solo_casillas_Mat.uasset
  Content/player/BP_PlayerActions.uasset
  Content/player/BP_PlayerC.uasset
  EscapeStalingradZ.uproject
  Source/EscapeStalingradZ/Grid/Grid.cpp
  Source/EscapeStalingradZ/Grid/Grid.h
  Source/EscapeStalingradZ/character/PlayerCharacter.h
  Source/EscapeStalingradZ/player/PlayerActions.cpp
  Source/EscapeStalingradZ/player/PlayerActions.h
  Source/EscapeStalingradZ/player/PlayerC.cpp
  Source/EscapeStalingradZ/player/PlayerC.h
  Source/EscapeStalingradZ/player/actions/ActionMovementForward.cpp
  Source/EscapeStalingradZ/player/actions/ActionMovementForward.h
  Source/EscapeStalingradZ/player/actions/Command.cpp
  Source/EscapeStalingradZ/player/actions/Command.h
  Source/EscapeStalingradZ/widget/WMovimiento.cpp
  Source/EscapeStalingradZ/widget/WMovimiento.h
  Source/EscapeStalingradZ/widget/buttons/MovementForward.cpp
  Source/EscapeStalingradZ/widget/buttons/MovementForward.h
Labels: Prioridad 1, Personaje

#88 Implementar Arco de Fuego
  Content/Character/BP_PlayerCharacter.uasset
  Content/Maps/InitialMap.umap
  Content/Maps/InitialMap_BuiltData.uasset
  Content/Widgets/W_MovementAction.uasset
  Content/art/materials/prueba.uasset
  Content/grid/BP_Grid.uasset
  Content/player/BP_PlayerPawn.uasset
  Source/EscapeStalingradZ/Grid/Grid.cpp
  Source/EscapeStalingradZ/Grid/Grid.h
  Source/EscapeStalingradZ/character/PlayerCharacter.cpp
  Source/EscapeStalingradZ/character/PlayerCharacter.h
  Source/EscapeStalingradZ/widget/WMovimiento.cpp
  Source/EscapeStalingradZ/widget/WMovimiento.h
  Source/EscapeStalingradZ/widget/buttons/Attack.cpp
  Source/EscapeStalingradZ/widget/buttons/Attack.h
Labels: Prioridad 1, Combate

#90 Linea de Fuego
  Content/Art/Materials/M_Arrow.uasset
  Content/Art/particles/LineOfFire.uasset
  Content/Maps/InitialMap.umap
  Content/Maps/InitialMap_BuiltData.uasset
  Content/Zombie/BP_Zombie.uasset
  Content/grid/BP_Grid.uasset
  Source/EscapeStalingradZ/Grid/Grid.cpp
  Source/EscapeStalingradZ/Grid/Grid.h
  Source/EscapeStalingradZ/character/PlayerCharacter.cpp
  Source/EscapeStalingradZ/character/PlayerCharacter.h
  Source/EscapeStalingradZ/zombies/Zombie.h
Labels: Prioridad 1, Combate

#91 Implementación selección objetivo
  Content/Art/particles/LineOfFire.uasset
  Content/Maps/InitialMap.umap
  Content/Maps/InitialMap_BuiltData.uasset
  Content/Widgets/W_MovementAction.uasset
  Content/grid/BP_Grid.uasset
  Source/EscapeStalingradZ/Grid/Grid.cpp
  Source/EscapeStalingradZ/Grid/Grid.h
  Source/EscapeStalingradZ/character/PlayerCharacter.cpp
  Source/EscapeStalingradZ/character/PlayerCharacter.h
  Source/EscapeStalingradZ/player/PlayerActions.cpp
  Source/EscapeStalingradZ/player/actions/ActionHandToHand.cpp
  Source/EscapeStalingradZ/player/actions/ActionHandToHand.h
  Source/EscapeStalingradZ/player/actions/ActionMovementBackward.cpp
  Source/EscapeStalingradZ/player/actions/ActionMovementForward.cpp
  Source/EscapeStalingradZ/player/actions/ActionMovementLateral.cpp
  Source/EscapeStalingradZ/player/actions/ActionNormalFire.cpp
  Source/EscapeStalingradZ/player/actions/ActionNormalFire.h
  Source/EscapeStalingradZ/player/actions/ActionSpreadFire.cpp
  Source/EscapeStalingradZ/player/actions/ActionSpreadFire.h
  Source/EscapeStalingradZ/player/actions/Command.cpp
  Source/EscapeStalingradZ/player/actions/Command.h
  Source/EscapeStalingradZ/widget/WMovimiento.cpp
  Source/EscapeStalingradZ/widget/WMovimiento.h
Labels: Prioridad 1, Combate

#93 Scoring a Hit
  Content/Character/BP_PlayerCharacter.uasset
  Content/Maps/InitialMap.umap
  Content/Maps/InitialMap_BuiltData.uasset
  Content/Widgets/W_MovementAction.uasset
  Source/EscapeStalingradZ/Grid/Grid.cpp
  Source/EscapeStalingradZ/character/PlayerCharacter.cpp
  Source/EscapeStalingradZ/character/PlayerCharacter.h
  Source/EscapeStalingradZ/zombies/Zombie.h
Labels: Prioridad 1, Combate

#96 Movimiento diagonal
  Content/Widgets/W_MovementAction.uasset
  Source/EscapeStalingradZ/Grid/Grid.cpp
  Source/EscapeStalingradZ/Grid/Grid.h
  Source/EscapeStalingradZ/player/actions/ActionDiagonalMovement.cpp
  Source/EscapeStalingradZ/player/actions/ActionDiagonalMovement.h
  Source/EscapeStalingradZ/widget/WMovimiento.cpp
  Source/EscapeStalingradZ/widget/WMovimiento.h
Labels: Prioridad 2, Personaje

#95 Casillas de fuego
  Config/DefaultEngine.ini
  Content/Art/Materials/M_modifiers.uasset
  Content/Maps/InitialMap.umap
  Content/Maps/InitialMap_BuiltData.uasset
  Content/grid/gridModifiers/BP_FireModifier.uasset
  Source/EscapeStalingradZ/Grid/Grid.cpp
  Source/EscapeStalingradZ/Grid/Grid.h
  Source/EscapeStalingradZ/Grid/GridModifier.cpp
  Source/EscapeStalingradZ/Grid/GridModifier.h
  Source/EscapeStalingradZ/character/PlayerCharacter.cpp
Labels: Prioridad 2, Mapas

#97 Rotación del personaje
  Content/Widgets/W_MovementAction.uasset
  Source/EscapeStalingradZ/Grid/Grid.cpp
  Source/EscapeStalingradZ/Grid/Grid.h
  Source/EscapeStalingradZ/player/actions/ActionMovementRotation.cpp
  Source/EscapeStalingradZ/player/actions/ActionMovementRotation.h
  Source/EscapeStalingradZ/widget/WMovimiento.cpp
  Source/EscapeStalingradZ/widget/WMovimiento.h
Labels: Prioridad 2, Personaje

#98 Casillas Hinder
  Content/Art/Materials/M_modifiers.uasset
  Content/Maps/InitialMap.umap
  Content/Maps/InitialMap_BuiltData.uasset
  Content/grid/gridModifiers/BP_FireModifier.uasset
  Content/grid/gridModifiers/BP_HinderModifier.uasset
  Source/EscapeStalingradZ/Grid/Grid.cpp
  Source/EscapeStalingradZ/Grid/Grid.h
  Source/EscapeStalingradZ/Grid/GridModifier.cpp
  Source/EscapeStalingradZ/character/PlayerCharacter.cpp
  Source/EscapeStalingradZ/character/PlayerCharacter.h
  Source/EscapeStalingradZ/player/actions/ActionDiagonalMovement.cpp
  Source/EscapeStalingradZ/player/actions/ActionMovementBackward.cpp
  Source/EscapeStalingradZ/player/actions/ActionMovementForward.cpp
  Source/EscapeStalingradZ/player/actions/ActionMovementLateral.cpp
  Source/EscapeStalingradZ/player/actions/ActionMovementRotation.cpp
Labels: Prioridad 2, Mapas

#99 Paredes
  Content/Maps/InitialMap.umap
  Content/Maps/InitialMap_BuiltData.uasset
  Content/grid/gridModifiers/BP_HinderModifier.uasset
  Content/grid/gridModifiers/BP_WallModifier.uasset
  Source/EscapeStalingradZ/Grid/Grid.cpp
  Source/EscapeStalingradZ/Grid/Grid.h
  Source/EscapeStalingradZ/Grid/GridModifier.cpp
  Source/EscapeStalingradZ/Grid/GridModifierWall.cpp
  Source/EscapeStalingradZ/Grid/GridModifierWall.h
  Source/EscapeStalingradZ/character/PlayerCharacter.cpp
Labels: Prioridad 2, Mapas

#100 Puertas
  Content/Maps/InitialMap.umap
  Content/Maps/InitialMap_BuiltData.uasset
  Content/grid/gridModifiers/BP_DoorModifier.uasset
  Source/EscapeStalingradZ/Grid/Grid.cpp
  Source/EscapeStalingradZ/Grid/Grid.h
  Source/EscapeStalingradZ/Grid/GridModifierDoor.cpp
  Source/EscapeStalingradZ/Grid/GridModifierDoor.h
  Source/EscapeStalingradZ/character/PlayerCharacter.cpp
  Source/EscapeStalingradZ/character/PlayerCharacter.h
Labels: Prioridad 2, Mapas

#102 Selección movimiento
  Content/Maps/InitialMap.umap
  Content/Maps/InitialMap_BuiltData.uasset
  Content/Widgets/BP_WCharacterButton.uasset
  Content/Widgets/BP_WSelectMovementType.uasset
  Content/Widgets/W_MovementAction.uasset
  Content/player/BP_PlayerC.uasset
  Source/EscapeStalingradZ/player/PlayerC.cpp
  Source/EscapeStalingradZ/player/PlayerC.h
  Source/EscapeStalingradZ/turn/Turn.cpp
  Source/EscapeStalingradZ/widget/CharacterButton.cpp
  Source/EscapeStalingradZ/widget/WMovimiento.cpp
  Source/EscapeStalingradZ/widget/WMovimiento.h
  Source/EscapeStalingradZ/widget/WSelectMovementType.cpp
  Source/EscapeStalingradZ/widget/WSelectMovementType.h
Labels: Prioridad 2, Personaje

#105 Implementar interfaz acciones principales
  Content/Widgets/BP_WActions.uasset
  Content/Widgets/BP_WSelectMovementType.uasset
  Content/Widgets/W_MovementAction.uasset
  Source/EscapeStalingradZ/widget/WActions.cpp
  Source/EscapeStalingradZ/widget/WActions.h
  Source/EscapeStalingradZ/widget/WMovimiento.h
  Source/EscapeStalingradZ/widget/WSelectMovementType.cpp
  Source/EscapeStalingradZ/widget/WSelectMovementType.h
Labels: Prioridad 2, Interfaces

#106 Interfaz acciones de movimiento
  Content/Widgets/BP_WActions.uasset
  Content/Widgets/BP_WMovementAction.uasset
  Content/Widgets/W_MovementAction.uasset
  Source/EscapeStalingradZ/Grid/Grid.cpp
  Source/EscapeStalingradZ/Grid/Grid.h
  Source/EscapeStalingradZ/widget/WActions.cpp
  Source/EscapeStalingradZ/widget/WMovimiento.cpp
  Source/EscapeStalingradZ/widget/WMovimiento.h
Labels: Prioridad 2, Interfaces

#109 Sistema de apertura/cierre puertas
  Content/Widgets/BP_WOtherActions.uasset
  Source/EscapeStalingradZ/Grid/Grid.cpp
  Source/EscapeStalingradZ/Grid/Grid.h
  Source/EscapeStalingradZ/player/actions/ActionOpenCloseDoor.cpp
  Source/EscapeStalingradZ/player/actions/ActionOpenCloseDoor.h
  Source/EscapeStalingradZ/widget/WOtherActions.cpp
  Source/EscapeStalingradZ/widget/WOtherActions.h
Labels: Prioridad 2, Personaje

#114 Normal Fire
  Content/Maps/InitialMap.umap
  Content/Maps/InitialMap_BuiltData.uasset
  Source/EscapeStalingradZ/character/PlayerCharacter.cpp
  Source/EscapeStalingradZ/character/PlayerCharacter.h
  Source/EscapeStalingradZ/player/actions/ActionNormalFire.cpp
  Source/EscapeStalingradZ/turn/Turn.cpp
  Source/EscapeStalingradZ/widget/CharacterButton.cpp
Labels: Prioridad 2, Combate

#115 Implementar turno zombie
  Config/DefaultEngine.ini
  Content/Maps/InitialMap.umap
  Content/Maps/InitialMap_BuiltData.uasset
  Content/Zombie/BP_Zombie.uasset
  Content/turn/BP_Turn.uasset
  Source/EscapeStalingradZ/Grid/Grid.cpp
  Source/EscapeStalingradZ/turn/Turn.cpp
  Source/EscapeStalingradZ/turn/Turn.h
  Source/EscapeStalingradZ/zombies/Zombie.cpp
Labels: Prioridad 2, Flujo de juego

#116 Iniciativa
  Source/EscapeStalingradZ/turn/Turn.cpp
  Source/EscapeStalingradZ/turn/Turn.h
  Source/EscapeStalingradZ/widget/WPlayerInfo.cpp
Labels: Prioridad 2, Flujo de juego

#117 Sistema de munición
  Content/Maps/InitialMap.umap
  Content/Maps/InitialMap_BuiltData.uasset
  Content/Widgets/BP_WCombat.uasset
  Source/EscapeStalingradZ/character/PlayerCharacter.cpp
  Source/EscapeStalingradZ/widget/WCombat.cpp
  Source/EscapeStalingradZ/widget/WCombat.h
Labels: Prioridad 2, Armas

#118 Selección de arma preparada
  Content/Maps/InitialMap.umap
  Content/Maps/InitialMap_BuiltData.uasset
  Content/Widgets/BP_WPlayerInfo.uasset
  Source/EscapeStalingradZ/widget/WActions.cpp
  Source/EscapeStalingradZ/widget/WPlayerInfo.cpp
  Source/EscapeStalingradZ/widget/WPlayerInfo.h
Labels: Prioridad 2, Armas

#119 Cambio botones normalFire y spreadFire
  Source/EscapeStalingradZ/widget/WCombat.cpp
  Source/EscapeStalingradZ/widget/WCombat.h
Labels: Combate
